sistema_empleados/empleados/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', EmpleadosListView.as_view(), name='lista-empleados'),
    path('crear_empleado/', EmpleadoCreateView.as_view(), name='crear-empleado'),
    path('actualizar_empleado/<int:pk>/', EmpleadoUpdateView.as_view(), name='actualizar-empleado'),
    path('eliminar_empleado/<int:pk>/', EmpleadoDeleteView.as_view(), name='eliminar-empleado'),
]

sistema_empleados/sistema_empleados/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('empleados.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

sistema_empleados/empleados/models.py
from django.db import models

# Create your models here.

class Empleado(models.Model):
    HOMBRE = 'H'
    MUJER = 'M'
    GENERO = [
        (HOMBRE, 'Hombre'),
        (MUJER, 'Mujer'),
    ]

    nombre_completo = models.CharField(max_length=255)
    telefono = models.CharField(max_length=25, blank=True, null=True)
    email = models.EmailField()
    edad = models.PositiveIntegerField()
    genero = models.CharField(max_length=1, choices=GENERO)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)


    def __str__(self):
        return f'{self.nombre_completo} + {self.genero}'
    
    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'

sistema_empleados/empleados/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from .models import Empleado
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin 

# Create your views here.

class EmpleadosListView(LoginRequiredMixin ,ListView):
    context_object_name = 'empleados'
    template_name = 'empleados/lista_empleados.html'
    paginate_by = 5

    def get_queryset(self):
        buscar_empleado = self.request.GET.get('q', '')
        lista = Empleado.objects.filter(nombre_completo__icontains=buscar_empleado)
        return lista
    
class EmpleadoCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Empleado
    fields = ('__all__')
    template_name = 'empleados/crear_empleado.html'
    success_url = reverse_lazy('lista-empleados')
    success_message = 'Empleado creado exitosamente.'

class EmpleadoUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Empleado
    fields = ('__all__')
    template_name = 'empleados/actualizar_empleado.html'
    success_url = reverse_lazy('lista-empleados')
    success_message = 'Empleado actualizado exitosamente.'

class EmpleadoDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Empleado
    template_name = 'empleados/eliminar_empleado.html'
    success_url = reverse_lazy('lista-empleados')
    success_message = 'Empleado eliminado exitosamente.'

sistema_empleados/empleados/templates/empleados/actualizar_empleado.html
{% extends 'empleados/base.html' %}

{% load static %}

{% block title %}Actualizar Empleado{% endblock title %}

{% block style %} {% static 'empleados/base.css' %} {% endblock style %}

{% block content %}

    <style>
        #id_nombre_completo, #id_telefono, #id_email, #id_edad, #id_genero {
            display: block;
            width: 100%;
        }

        #id_genero {
            text-align: center;
        }

        .nombre-modelo {
            text-transform: uppercase;
            font-weight: bold;
        }
    </style>

    <form method="post" class="text-center form-control" style="margin: 100px auto 0px auto; max-width: 800px; border: 1px solid black;">{% csrf_token %}
        <div>
            <label for="" class="nombre-modelo">Nombre completo</label>
            <span class="form-control">{{ form.nombre_completo }}</span>
        </div>
        <div>        
            <label for="" class="nombre-modelo">Telefono</label>
            <span class="form-control">{{ form.telefono }}</span>
        </div>
        <div>
            <label for="" class="nombre-modelo">Email</label>
            <span class="form-control">{{ form.email }}</span>
        </div>
        <div>
            <label for="" class="nombre-modelo">Edad</label>
            <span class="form-control">{{ form.edad }}</span>
        </div>
        <div>
            <label for="" class="nombre-modelo">Genero</label>
            <span class="form-control">{{ form.genero }}</span>
            
        </div>
        <input type="submit" value="Actualizar empleado" class="btn btn-primary form-control" style="margin-top: 20px;">
        <a href='{% url "lista-empleados" %}' class='btn btn-success' style="margin-top: 20px; display: block;">Regresar</a>
    </form>
{% endblock content %}

sistema_empleados/empleados/templates/empleados/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% block style %}{% endblock style %}"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d9e5d623d1.js" crossorigin="anonymous"></script>
</head>
<body>

    <nav class="nav justify-content-evenly align-items-center bg-black text-white p-2">
        <a class="m-0" href="{% url 'lista-empleados' %}" style="color: white; font-size: 25px; text-decoration: none;"><i class="fa-solid fa-rectangle-list"></i> Empleados</a>
    {% if user.is_authenticated %}
        <span class=""><i class="fa-solid fa-user"></i> {{ user.get_username }}</span>
        <a href="{% url 'logout' %}" class="btn btn-danger">Salir</a>
    {% else %}
        {% block ingresar %}{% endblock ingresar %}
    {% endif %}
    </nav>

    <div class="container-fluid" style="margin: 0; padding: 0;">

        {% block content %}{% endblock content %}

    </div>


    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
</body>
</html>

sistema_empleados/empleados/templates/empleados/crear_empleado.html
{% extends 'empleados/base.html' %}

{% load static %}

{% block title %}Crear Empleado{% endblock title %}

{% block style %} {% static 'empleados/base.css' %} {% endblock style %}

{% block content %}

    <style>
        #id_nombre_completo, #id_telefono, #id_email, #id_edad, #id_genero {
            display: block;
            width: 100%;
        }

        #id_genero {
            text-align: center;
        }

        .nombre-modelo {
            text-transform: uppercase;
            font-weight: bold;
        }
    </style>

    <form method="post" class="text-center form-control" style="margin: 100px auto 0px auto; max-width: 800px; border: 1px solid black;">{% csrf_token %}
        <div>
            <label for="" class="nombre-modelo">Nombre completo</label>
            <span class="form-control">{{ form.nombre_completo }}</span>
        </div>
        <div>        
            <label for="" class="nombre-modelo">Telefono</label>
            <span class="form-control">{{ form.telefono }}</span>
        </div>
        <div>
            <label for="" class="nombre-modelo">Email</label>
            <span class="form-control">{{ form.email }}</span>
        </div>
        <div>
            <label for="" class="nombre-modelo">Edad</label>
            <span class="form-control">{{ form.edad }}</span>
        </div>
        <div>
            <label for="" class="nombre-modelo">Genero</label>
            <span class="form-control">{{ form.genero }}</span>           
        </div>
        
        <input type="submit" value="Crear empleado" class="btn btn-primary form-control" style="margin-top: 20px;">
        <a href='{% url "lista-empleados" %}' class='btn btn-success' style="margin-top: 20px; display: block;">Regresar</a>
    </form>
{% endblock content %}

sistema_empleados/empleados/templates/empleados/eliminar_empleado.html
{% extends 'empleados/base.html' %}

{% load static %}

{% block title %}Eliminar empleado{% endblock title %}

{% block style %} {% static 'empleados/base.css' %} {% endblock style %}

{% block content %}
    <form method="post" class="text-center form-control" style="margin: 100px auto 0px auto; max-width: 800px; border: 1px solid black;">{% csrf_token %}
    <p>Seguro quieres eliminar al siguiente empleado?</p>
    <p>Nombre: {{ empleado.nombre_completo }}</p>
    <p>Telefono: {{ empleado.telefono }}</p>
    <p>Email: {{ empleado.email }}</p>
    <p>Edad: {{ empleado.edad }}</p>
    <p>Genero: {{ empleado.genero }}</p>
    <p>Fecha creacion: {{ empleado.fecha_creacion }}</p>
    {{ form }}
    <input type="submit" value="Confirmar" class='btn btn-primary'>
    <a href='{% url "lista-empleados" %}' class='btn btn-success'>Regresar</a>
    </form>
{% endblock content %}

sistema_empleados/empleados/templates/empleados/lista_empleados.html
{% extends 'empleados/base.html' %}

{% load static %}

{% block style %} {% static 'empleados/base.css' %} {% endblock style %}

{% block title %}Lista empleados{% endblock title %}

{% block ingresar %}<a href="{% url 'login' %}" class="btn btn-primary">Ingresar</a>{% endblock ingresar %}

{% block content %}

    {% if messages %}
    <ul class="messages" style="list-style: none; padding: 0;">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }} alert alert-success" role="alert" {% endif %} style="margin: 15px 20px 0 20px; text-align: center;">{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <nav class="nav justify-content-evenly" style="margin-top: 20px;">
        <form action="#" method="get" class="d-flex align-items-center">
            <input name="q" id='q' type="text" placeholder="Buscar empleado..." class="form-control">
            <button class="btn btn-primary" style="margin-left: 5px;"><i class="fa-solid fa-magnifying-glass"></i></button>
        </form>
        <a href="{% url 'crear-empleado' %}" class="btn btn-primary my-3"><i class="fa-solid fa-plus" style="margin-right: 5px;"></i>Agregar empleado</a>
    </nav>

    <div class="table-responsive" style="max-width: 1200px; margin: 40px auto 0 auto;">
        <table class="table table-striped table-dark" style="margin-top: 20px;">
            <thead class="table-info border-1">
                <tr class="text-center">
                <th scope="col">Nombre</th>
                <th scope="col">Telefono</th>
                <th scope="col">Email</th>
                <th scope="col">Edad</th>
                <th scope="col">Genero</th>
                <th scope="col">Registrado</th>
                <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for i in empleados %}
                <tr class="text-center">
                <td style="vertical-align: middle;">{{ i.nombre_completo }}</td>
                <td style="vertical-align: middle;">{{ i.telefono }}</td>
                <td style="vertical-align: middle;">{{ i.email }}</td>
                <td style="vertical-align: middle;">{{ i.edad }}</td>
                <td style="vertical-align: middle;">{{ i.genero }}</td>
                <td style="vertical-align: middle;">{{ i.fecha_creacion }}</td>
                <td style="vertical-align: middle;">
                    <a href="{% url 'actualizar-empleado' i.id %}" class="btn btn-outline-warning"><i class="fa-solid fa-pen-to-square fa-xl"></i></a>
                    <a href="{% url 'eliminar-empleado' i.id %}" class="btn btn-outline-danger"><i class="fa-solid fa-trash fa-xl"></i></a>
                </td>
                </tr>
                {% empty %}
                <p>Todavia no hay ningun empleado almacenado.</p>
                {% endfor %}
            </tbody>
        </table>

        <div class="pagination form-control" style="display: block; text-align: center;">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1" class="btn btn-secondary">&laquo; Primera</a>
                    <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary">Anterior</a>
                {% endif %}
        
                <span class="current">
                    <span style="text-transform: capitalize; font-weight: bold; margin: 15px;">Pagina {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</span>
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary">Siguiente</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}" class="btn btn-secondary">Ultima &raquo;</a>
                {% endif %}
            </span>
        </div>

    </div>

{% endblock content %}